"""Script Agent stub — would be an LLM writing movie-script parts.

Returns a deterministic scene-text string echoing the brief and canonical characters so the
downstream gates have realistic content to evaluate without any model dependency.
"""

from __future__ import annotations

from ..core.types import Action, Context


class ScriptAgent:
    node_id = "script_agent"
    kind = "generate_script"

    def run(self, action: Action, context: Context) -> str:
        brief = action.payload.strip()
        characters = (context.character_bible or {}).get("characters", [])
        cast = ", ".join(characters[:2]) if characters else "the protagonist"
        return (
            f"SCENE 1 — INT. STORYBOARD\n"
            f"Logline: {brief}\n"
            f"{cast} appear on screen and advance the story beat described above.\n"
            f"[stub script generated by ScriptAgent]"
        )
