"""Image Generation Agent stub — would be a diffusion model.

Returns a small descriptor dict instead of pixels so the pipeline stays dependency-free.
"""

from __future__ import annotations

from typing import Any

from ..core.types import Action, Context


class ImageAgent:
    node_id = "image_agent"
    kind = "generate_image"

    def run(self, action: Action, context: Context) -> dict[str, Any]:
        return {
            "type": "image",
            "format": "png",
            "prompt": action.payload,
            "pixels": "<stub-bytes>",
            "note": "stub image generated by ImageAgent",
        }
