"""Video Generation Agent stub — would be a video diffusion model."""

from __future__ import annotations

from typing import Any

from ..core.types import Action, Context


class VideoAgent:
    node_id = "video_agent"
    kind = "generate_video"

    def run(self, action: Action, context: Context) -> dict[str, Any]:
        return {
            "type": "video",
            "format": "mp4",
            "prompt": action.payload,
            "frames": "<stub-frames>",
            "duration_s": 4,
            "note": "stub video generated by VideoAgent",
        }
